### ISSUE TITLE
Add support for GetUnhandledUpdateNames

### ISSUE THREAD

**Issue by antlai-temporal** [temporalio/sdk-go#1316]
With signals we can define a catch-all handler by using `GetUnhandledSignalNames`, which will be called if there are no specific handlers registered for a signal name. 

There is no equivalent for updates at this point, so the proposal is to create a `GetUnhandledUpdateNames` that mimics the signals implementation.

**Comment by Quinn-With-Two-Ns** [comment]
I agree we should have a way to add a catch all,  I don't think we should mimic the signal approach since updates and signal have 
 very different APIs and behavior in the Go SDK.  One example is we say we want update handlers to run before the main workflow function, with `GetUnhandledUpdateNames` that is not possible
 
 I think we should allow registering a catch all handler. In other SDKs we call these dynamic handlers.

**Comment by antlai-temporal** [comment]
Makes sense, shall we close this one and open a more generic catch all for update?

**Comment by cretz** [comment]
Per https://github.com/temporalio/features/issues/201, I made this part of https://github.com/temporalio/sdk-go/issues/997.
