### ISSUE TITLE
Simplify the update-wth-start API

### ISSUE THREAD

**Issue by shizambles** [temporalio/sdk-go#1728]
**Is your feature request related to a problem? Please describe.**

The new, experimental update-with-start API provides a confusing API. Looking at the [integration test code](https://github.com/temporalio/sdk-go/pull/1579/files#diff-8118e44ac15fb5ab2e2ece2ab52fd23062a10b5cc9c55ee5b3620a1242cff27cR3992), it appears that the way to update-wth-start an already running workflow is to call [Client.ExecuteWorkflow()](https://pkg.go.dev/go.temporal.io/sdk@v1.30.0/client#Client) twice. 

1. The first call to `ExecuteWorkflow`, needs a `StartWorkflowOptions` with `WorkflowIDConflictPolicy` set to `WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING`. The documentation of this policy states -
```go
// Don't start a new workflow; instead return a workflow handle for the running workflow.
WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING WorkflowIdConflictPolicy = 2
```
2. The second call to `ExecuteWorkflow`, needs a `StartWorkflowOptions` with `WithStartOperation` set to a `NewUpdateWithStartWorkflowOperation` value like below.
```go
client.NewUpdateWithStartWorkflowOperation(
		client.UpdateWorkflowOptions{
			UpdateName:   "update",
			Args:         ....,
			WaitForStage: client.WorkflowUpdateStageCompleted,
		})
```
The documentation of `WithStartOperation` states - 
```go
// WithStartOperation - Operation to execute with Workflow Start.
// For example, see NewUpdateWithStartWorkflowOperation to perform Update-with-Start. Note that if the workflow is
// already running and WorkflowIDConflictPolicy is set to UseExisting, the start is skipped and only the
// operation is executed.
```

Needing two consecutive calls to `ExecuteWorkflow` to exercise the update-with-start functionality is confusing and in my opinion violates the principle of least surprise. The developer is now having to drill down into the documentation to realize that despite the documentation for `ExecuteWorkflow` stating that `ExecuteWorkflow starts a workflow execution and returns a WorkflowRun instance or error`, it many not actually start a workflow depending on what options are passed in.

**Describe the solution you'd like**

The API could be simplified by providing a single suitably named function - say `client.UpdateWithStartWorkflow` that hides the above details and does the needful.

**Comment by dandavison** [comment]
Hi @shizambles, we're in the process of rolling out update-with-start across all languages and we are indeed planning to make an API change here. I'll update this ticket with details when the relevant PRs are merged, but what we're planning is similar to what you suggest.

That said, your interpretation of the current API isn't quite right. UpdateWithStart requires only one call to `ExecuteWorkflow`, for example, see the sample here: https://github.com/temporalio/samples-go/blob/main/early-return/starter/main.go

The integration test you point to calls `ExecuteWorkflow` twice -- once to start a workflow, and a second time to confirm that an Update-With-Start can be sent to an already-running workflow. To test this style of usage of Update-With-Start, the second call has to pass the `USE_EXISTING` workflow ID conflict policy. This style of UwS usage is intended for situations where you have a relatively long-running workflow (e.g. an e-commerce shopping cart, or an "entity" workflow acting as a service of some sort), and you want to send an update to the workflow, starting it if necessary.

The other style of Update-With-Start usage involves using the (default) `FAIL` conflict policy. This is for when you want to start a workflow and at the same time send an update in the first workflow task, and you want the operation to fail if the workflow already exists (i.e. you demand that a workflow is _started_). This style is what is shown in the [sample](https://github.com/temporalio/samples-go/blob/main/early-return/starter/main.go).

It's important to understand that the concept of the workflow ID conflict policy is not specifically tied to Update-With-Start: it's available whenever you start a workflow, allowing you to control what happens when the workflow ID you supply corresponds to an already-running workflow. In other words, it's already the case, across all SDKs, that the start-workflow API can be used in an idempotent style that will succeed without actually starting a workflow, if it exists already. So it isn't specifically related to update-with-start, but understanding that option is central to understanding the two usage modes of update-with-start.

I'll ping this ticket when we make the planned changes!

**Comment by dandavison** [comment]
The modified update-with-start API has now been released. See https://github.com/temporalio/sdk-go/releases/tag/v1.31.0 and API docs  https://pkg.go.dev/go.temporal.io/sdk@v1.31.0/client#Client.UpdateWithStartWorkflow
