### ISSUE TITLE
CancelWorkflow() should return EntityNotExistsError error if workflow does not exist

### ISSUE THREAD

**Issue by ingyamilmolinar** [temporalio/sdk-go#395]
## Expected Behavior
Running CancelWorkflow(ctx, workflowID, "") by using an ID of a workflow that does not exist or that has no execution instances should return EntityNotExistsError error that is friendly with the standard `errors` package.

## Actual Behavior
The function is returning:
```
reflect.TypeOf(err) = *serviceerror.NotFound
err.Error() = sql: no rows in result set
```

So far, to distinguish this error from the rest, I need to assert the error: `_, isNotFound := err.(*serviceerror.NotFound)` which works but it's a non standard way to verify error types. I am unable to use the errors package `Is()` function.

## Steps to Reproduce the Problem

  1. Use CancelWorkflow with a non existent or terminated workflow ID and get the error
  2. errors.Is(err, &serviceerror.NotFound{}) will be false.

## Specifications

  - SDK Version: 1.5.0
  - Platform: Linux Debian 5.7.10 x86_64 GNU/Linux

**Comment by Gibstick** [comment]
I think this is still happening. The issue also occurs with `GetWorkflow`. I'm on SDK Version 1.15.0.

**Comment by cretz** [comment]
> which works but it's a non standard way to verify error types. 

This is not true. It _is_ the standard way to verify error types. `errors.Is` is the standard way to verify _equality_. But this is a server error and you don't want to verify equality (the message the server may relay for not-found is not known), you want to verify that it is not found for any reason.

@Gibstick - Is this the problem you are having? That you are using `errors.Is` to assert type instead of using a type assertion?

**Comment by cretz** [comment]
:+1: Closing issue. Original report was incorrect in assuming how you check for error types in Go.
