### ISSUE TITLE
Can't use `errors.Is` to check a returned error

### ISSUE THREAD

**Issue by esdrasbeleza** [temporalio/sdk-go#403]
(Moving https://github.com/temporalio/temporal/issues/1453 here, as I think I created it in the wrong place)

## Expected Behavior

If an activity returns an error from some custom error from my system, it's wrapped and I can check it using `errors.Is`.

## Actual Behavior

My error message is wrapped there, but I can't compare/check it.

## Steps to Reproduce the Problem

```golang
var ErrNotFound = errors.New("not found!")

func TestWorkflowTestSuite(t *testing.T) {
	suite.Run(t, new(WorkflowTestSuite))
}

type WorkflowTestSuite struct {
	suite.Suite
	testsuite.WorkflowTestSuite
	env *testsuite.TestWorkflowEnvironment
}

func (s *WorkflowTestSuite) SetupTest() {
	s.env = s.NewTestWorkflowEnvironment()
}

func (s *WorkflowTestSuite) TearDownTestSuite() {
	s.env.AssertExpectations(s.T())
}

func (s *WorkflowTestSuite) Test_WorkflowErrorHandling() {
	activity := func(number int) error {
		return fmt.Errorf("error: %w", ErrNotFound)
	}
	s.env.RegisterActivity(activity)

	workflow := func(ctx workflow.Context, number int) error {
		ctx = workflow.WithActivityOptions(ctx, workflow.ActivityOptions{
			StartToCloseTimeout: time.Minute,
			RetryPolicy: &temporal.RetryPolicy{
				MaximumAttempts:    3,
				BackoffCoefficient: 2,
			},
		})

		if err := workflow.ExecuteActivity(ctx, activity, number).Get(ctx, nil); err != nil {
			return err
		}

		return nil
	}
	s.env.RegisterWorkflow(workflow)
	s.env.ExecuteWorkflow(workflow, 123)

	s.True(s.env.IsWorkflowCompleted())
	err := s.env.GetWorkflowError()
	s.ErrorIs(err, ErrNotFound)
}
```

The result will be:

```
Error:      	Target error should be in err chain:
                    expected: "not found!"
                    in chain: "workflow execution error (type: func2, workflowID: default-test-workflow-id, runID: default-test-run-id): activity error (type: func1, scheduledEventID: 0, startedEventID: 0, identity: ): error: not found! (type: wrapError, retryable: true): not found!"
                        "activity error (type: func1, scheduledEventID: 0, startedEventID: 0, identity: ): error: not found! (type: wrapError, retryable: true): not found!"
                        "error: not found! (type: wrapError, retryable: true): not found!"
                        "not found!"
```

## Specifications

  - Version: v1.5.0; 1.6.0
  - Platform: macOS

**Comment by daveworth** [comment]
Adding a note here after a conversation in the [Temporal Slack #go-sdk channel](https://temporalio.slack.com/archives/CTDTU3J4T/p1622670551047200).  In addition to the issue raised here, though by design, the documentation both on the website and in the code imply three different methods for getting the original error, none of which are implemented:

1. The documentation on [Go Error Handling](https://docs.temporal.io/docs/go/error-handling/) states that there is an `err.OriginalType()` method which can be used to get the original error either as a string or as an actual error type.
2. The code comments in `internal/error.go` also have two different documented methods in the same block:  [here](https://github.com/temporalio/sdk-go/blob/master/internal/error.go#L50) it states that there is `err.GetOriginalType()` while [here](https://github.com/temporalio/sdk-go/blob/master/internal/error.go#L78) it states that there is `err.Type()`. The latter _does_ exist and returns a string.

In general I wonder if a documentation improvement may be in order to capture the contents of this issue and make the calls more consistent in their usage in those three places?

Thank you!

**Comment by mfateev** [comment]
We certainly need to add `Is` method to all Temporal returned errors. For example, the following code doesn't work:
```
	s.True(errors.Is(workflowErr, &temporal.CanceledError{}), workflowErr)
```
as `CanceledError` doesn't implement the `Is` method.

**Comment by alexshtin** [comment]
It doesn't work and it shouldn't. `errors.Is` is equality function, i.e. it checks if returned error chain contains exactly the same error object. And by default it compares pointers which doesn't work in our case at all, because we reconstruct errors every time they cross process boundaries. We can override `Is` method for our errors, but it should do deep compare of every field, not only type assertion because empty `CanceledError` and `CanceledError` with details are not equal. And `ApplicationError` with different message or `errType` are also not the same and checking them with `errors.Is` should return false.

There is `errors.As` also which works as type assertion. So if you want to check if `workflowErr` contains any`CanceledError` in error chain you should do:
```go
var canceledErr *temporal.CanceledError
s.True(errors.As(workflowErr, &canceledErr))
```
I agree, this is little bit cumbersome but it is what it is in the Go world. And this perfectly works with all Temporal errors because they all has `Unwrap` method.
