### ISSUE TITLE
JSON Serialization Errors From Activity Responses Fail Silently

### ISSUE THREAD

**Issue by DannyHinshaw** [temporalio/sdk-go#432]
## Expected Behavior

When an Activity tries to return a non-serializable type (such as an `error`), an error should be presented in the worker logs.

## Actual Behavior

Currently the error is not output to logs, however it is possible to discover the issue by visiting the Temporal web app and inspect the Workflow execution history.

## Steps to Reproduce the Problem

  1. Return a struct with an `error` type attached to it from an Activity (make sure the response is an error and not `nil`).
  1. See the Workflow fails
  1. See there is no logging output in the worker logs.
  
  If you wish, I made a repo with a branch to repro this issue here: https://github.com/DannyHinshaw/go-temporal-sandbox/tree/issue/bad-json-silent-failure
  You can clone that, run `docker-compose up -d` and then hit the endpoint `GET http://localhost:8080/workflow` to trigger a workflow that shows the issue. From there you can inspect the system logs and Temporal web app.

**Comment by vitarb** [comment]
Thanks for reporting this issue, failing silently definitely doesn't sound right, we'll take a look at it!

**Comment by vitarb** [comment]
I've debugged this a bit and it looks like the problem is with default json converter, that returns no error if you marshal a struct with an error field into json, but then fails to unmarshal it back.
Consider following test code (passes):
```

	pc := NewJSONPayloadConverter()

	wt := testStructWithError{Name: "qwe", Error: errors.New("some error")}
	payload, err := pc.ToPayload(wt)
	require.NoError(t, err) // Should this be an error since it's impossible to deserialize?

	var deserialized testStructWithError
	err = pc.FromPayload(payload, &deserialized)
	require.Error(t, err)
	assert.Equal(t, "unable to decode: json: cannot unmarshal object into Go struct field testStructWithError.Error of type error", err.Error())
```

So the reason why this doesn't produce any message when you complete an activity is because underlying json serializer succeeds and we successfully ship bytes back to the server, and it fails only when we try to process subsequent workflow task, which fails to deserialize the payload. I'm not sure if there is a good general solution to this issue, but there seem to be a work-around for passing an error described [here](http://blog.magmalabs.io/2014/11/13/custom-error-marshaling-to-json-in-go.html).

**Comment by vitarb** [comment]
I'm going to resolve this issue for now, please reopen if you have more questions or find response unsatisfactory.
