### ISSUE TITLE
Vulnerability CVE-2021-3121

### ISSUE THREAD

**Issue by W0nderMuffin** [temporalio/sdk-go#468]
The `github.com/gogo/status:v1.1.0` dependency includes a  vunerability by using outdated protobuf `github.com/gogo/protobuf v1.2.0`

## CVE-2021-3121
An issue was discovered in GoGo Protobuf before 1.3.2. plugin/unmarshal/unmarshal.go lacks certain index validation, aka the "skippy peanut butter" issue.

https://nvd.nist.gov/vuln/detail/CVE-2021-3121

**Comment by vitarb** [comment]
SDK [is using](https://github.com/temporalio/sdk-go/blob/master/go.mod#L8) `1.3.2` for a while now.

Here is dependency graph:
```
❯ go mod graph | grep "gogo/protobuf"
go.temporal.io/sdk github.com/gogo/protobuf@v1.3.2
github.com/gogo/protobuf@v1.3.2 github.com/kisielk/errcheck@v1.5.0
github.com/gogo/protobuf@v1.3.2 github.com/kisielk/gotool@v1.0.0
github.com/gogo/protobuf@v1.3.2 golang.org/x/tools@v0.0.0-20210106214847-113979e3529a
github.com/gogo/status@v1.1.0 github.com/gogo/protobuf@v1.2.0
github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0 github.com/gogo/protobuf@v1.3.2
go.temporal.io/api@v1.4.1-0.20210420220407-6f00f7f98373 github.com/gogo/protobuf@v1.3.2
github.com/gogo/googleapis@v1.4.1 github.com/gogo/protobuf@v1.3.2
```

Latest `gogo/status` is still relying on `v1.2.0`, which I believe is why we see this version in the `go.sum` as well.
But since we have `v1.3.2` in the `go.mod` file, it is the on that is actually in use.

```
❯ go list -m -json all | grep -A2 "gogo/protobuf"
	"Path": "github.com/gogo/protobuf",
	"Version": "v1.3.2",
	"Time": "2021-01-10T08:01:47Z",
	"Dir": "/home/vit/go/pkg/mod/github.com/gogo/protobuf@v1.3.2",
	"GoMod": "/home/vit/go/pkg/mod/cache/download/github.com/gogo/protobuf/@v/v1.3.2.mod",
	"GoVersion": "1.15"
}
```

I'm going to close this one, please let me know if you have more questions.
