### ISSUE TITLE
Add accessors for ActivityError fields

### ISSUE THREAD

**Issue by aocole** [temporalio/sdk-go#496]
**Is your feature request related to a problem? Please describe.**
When handling an ActivityError from a workflow, it would be nice to be able to access some of the fields of the ActivityError such as retryState.

**Describe the solution you'd like**
I would like exported accessor functions on ActivityError to access fields such as retryState

**Additional context**
[Discussed in the forums](https://community.temporal.io/t/questions-around-activity-errors-retry-and-more-complex-error-handling-scenarios/2016/9?u=aocole) and Maxim requested this issue.

**Comment by vitarb** [comment]
Out of all fields
```
	ActivityError struct {
		temporalError
		scheduledEventID int64
		startedEventID   int64
		identity         string
		activityType     *commonpb.ActivityType
		activityID       string
		retryState       enumspb.RetryState
		cause            error
	}
```
cause is already exposed via `Unwrap`

while `Error` function provides details for activity type, scheduled/started event IDs and identity:
```
func (e *ActivityError) Error() string {
	msg := fmt.Sprintf("%s (type: %s, scheduledEventID: %d, startedEventID: %d, identity: %s)", e.message(), e.activityType.GetName(), e.scheduledEventID, e.startedEventID, e.identity)
	if e.cause != nil {
		msg = fmt.Sprintf("%s: %v", msg, e.cause)
	}
	return msg
}
```
I think for convenience reasons we should also provide values for the above variables so that users are not forced to parse the string if they need these details inside of the workflow.
Also we should add getters for two missing fields - RetryState and ActivityID.
Now the question is, if we should do the same for other error types, here is a full list:
```
ApplicationError
CanceledError
ServerError
ChildWorkflowExecutionError
WorkflowExecutionError
TimeoutError
TerminatedError
PanicError
UnknownExternalWorkflowExecutionError
```
