### ISSUE TITLE
Activity mocking in test framework not able to do exact match of arguments

### ISSUE THREAD

**Issue by roselander** [temporalio/sdk-go#586]
## Expected Behavior

Should be able to specify exact input struct to match when calling `OnActivity`.

## Actual Behavior

Error: `Unexpected Metho
[delete_role.txt](https://github.com/temporalio/
[delete_role_activities.txt](https://github.com/temporalio/sdk-go/files/7341180/delete_role_activities.txt)
sdk-go/files/7341171/delete_role.txt)
d Call`, and actual activity input observed by test environment is missing field which I know is set by the workflow. Output:

```
	mock: Unexpected Method Call
	-----------------------------
	DeleteRole2(*auth0.DeleteRoleActivities,<nil>,auth0.DeleteRoleActivityInput)
			0: &auth0.DeleteRoleActivities{auth0:auth0.Auth0(nil)}
			1: <nil>
			2: auth0.DeleteRoleActivityInput{RoleName:""}
	The closest call I have is:
	DeleteRole2(string,string,auth0.DeleteRoleActivityInput)
			0: "mock.Anything"
			1: "mock.Anything"
			2: auth0.DeleteRoleActivityInput{RoleName:"test-role"}
```
[delete_role_test.txt](https://github.com/temporalio/sdk-go/files/7341185/delete_role_test.txt)

## Steps to Reproduce the Problem

See attached WF, Activity, and Unit Test.

**Comment by cretz** [comment]
Please feel free to reopen if your issue remains unresolved. Thanks!

**Comment by laniehei** [comment]
How do I mock an activity input that involves a pointer? e.g. 

```
type DeleteRoleActivityInput struct {
     Role *string 
}
testRole := "testRole"
s.env.OnActivity(
		new(DeleteRoleActivities).DeleteRole2,
		mock.Anything,
		DeleteRoleActivityInput{Role: &testRole},
	).Return(
		DeleteRoleActivityOutput{},
		nil,
	)
```

It fails when I test the given workflow because 'testRole' is a different spot in memory.

**Comment by cretz** [comment]
The mocking library is https://pkg.go.dev/github.com/stretchr/testify/mock so the parameter matching is done via https://pkg.go.dev/github.com/stretchr/testify/mock#Mock.On. I am not an expert on that mocking library, but it seems that except for some special cases, it just does equality check. In Go, equality check on pointers means they must point to the same thing (so that literal `testRole` variablem, ref https://go.dev/ref/spec#Comparison_operators).

Usually though, when you mock, you don't need to be so specific on the argument types to do your assertion. Per https://pkg.go.dev/go.temporal.io/sdk/internal#TestWorkflowEnvironment.OnActivity we made a special case where you can provide a callback here, and in there you can assert exact data. If you _really_ wanted to have advanced matching though, you could do something like (untested):

```go
s.env.OnActivity(
  new(DeleteRoleActivities).DeleteRole2,
  mock.Anything,
  mock.MatchedBy(func(in *DeleteRoleActivityInput) bool { return *in.Role == "testRole" }),
)
```

(Also note, in Go pointers to primitives are usually discouraged if just using for knowing `nil` vs value. If the difference between empty string and `nil` is significant it can make sense, but otherwise treating an empty string as unset is clearer.)

**Comment by roselander** [comment]
Is there any reason not to throw a descriptive error if someone uses the `(*Activities).Activity` invocation?

**Comment by cretz** [comment]
Kinda. In Go, `(*SomeStruct).Function(string)` and `Function(*SomeStruct, string)` look the same at runtime. Technically I can do some advanced things to confirm whether that first param is a receiver or not maybe, but I think it's technically ok to register `(*SomeStruct).Function(string)` and accept `*SomeStruct` as the first param, so not sure we should explicitly prevent it.
