### ISSUE TITLE
Logs are not added to OpenTracing Spans when tracing is enabled

### ISSUE THREAD

**Issue by pimvanhespen** [temporalio/sdk-go#802]
## Expected Behavior
I have enabled tracing via the OpenTracing interceptor.  I would expect logs within a tracing scope to be logged to their respective spans. 

## Actual Behavior
The logs are not propagated to the Spans. 

Within the `tracingWorkflowOutboundInterceptor` (vendor/go.temporal.io/sdk/interceptor/tracing_interceptor.go:490) a call is made to `BaseTracer.GetLogger(log.logger, TracerSpanRef)`. The TracerSpanRef is ignored and the tracing information is lost.

## Steps to Reproduce the Problem

  1. Create an empty workflow
  1. Retrieve the logger via `workflow.GetLogger(ctx)`
  1. Log a line of information
  2. check the output (in this case via the docker image jaeger-all-in-one:latest)
  3. Inspect a trace
  4. Inspect the workflow Span
  5. Check the logs related to the Span
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6585005/167386243-d84bc2cc-b2a4-4c8e-acc9-8140adfbe8d5.png">

## Specifications

  - Version: 
    - go.temporal.io/sdk v1.14.0
    - go.temporal.io/sdk/contrib/opentelemetry v0.1.0
    - go.opentelemetry.io/otel v1.6.1
    - go.opentelemetry.io/otel/exporters/jaeger v1.6.1
    - go.opentelemetry.io/otel/sdk v1.6.1
    
  - Platform:
    - macOS 12.3, Ubuntu 18.04

**Comment by cretz** [comment]
The default implementation of `GetLogger` intentionally does not apply logs to the trace. The `GetLogger` method was added by DataDog at #655 since they want to implement their own `interceptor.Tracer` that overrides that and _does_ provide a tracing enabled logger. By default we don't want all user logs to appear in traces. But if this is important for you, you can implement your own tracer, probably wrapping/delegating to the ones that exist, but providing your own `GetLogger` impl that does attach logs to traces.

**Comment by pimvanhespen** [comment]
Hi @cretz, thank you very much for your explanation!
