### ISSUE TITLE
MutableSideEffect doesn't seem to work

### ISSUE THREAD

**Issue by dnr** [temporalio/sdk-go#803]
## Expected Behavior
MutableSideEffect works as described in the docs.

## Actual Behavior
This code:
```
	// load default number
	get := func(ctx workflow.Context) interface{} { return defaultNumber }
	eq := func(a, b interface{}) bool { return a.(int) == b.(int) }
	var number int
	if err := workflow.MutableSideEffect(ctx, "defaultNumber", get, eq).Get(&number); err != nil {
		panic("can't decode number:" + err.Error())
	}
```
works at first, but if I kill and restart the worker to force replay, I get:
```
2022/05/09 18:16:00 ERROR Workflow panic Namespace default TaskQueue hello-world WorkerID 2450384@pinglin@ WorkflowType Workflow WorkflowID hello_world_workflowID RunID 408db9e3-7885-4ca5-be59-0bce212c08eb Attempt 1 Error can't decode number:payload item 0: unable to decode: json: cannot unmarshal string into Go value of type int StackTrace coroutine root [panic]:
github.com/temporalio/samples-go/helloworld.Workflow({0xdfce40, 0xc00043a580}, {0xc0004360f8, 0x8})
        /home/dnr/t/samples-go/helloworld/helloworld.go:21 +0x23d
reflect.Value.call({0xbe9b60?, 0xd38768?, 0x30?}, {0xcd73c3, 0x4}, {0xc00040d1d0, 0x2, 0x18?})
        /nix/store/f2n8g9nbrxaqwyd9b3grynvwhyz3qlrw-go-1.18/share/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0xbe9b60?, 0xd38768?, 0xc000407d28?}, {0xc00040d1d0, 0x2, 0x2})
        /nix/store/f2n8g9nbrxaqwyd9b3grynvwhyz3qlrw-go-1.18/share/go/src/reflect/value.go:339 +0xbf
go.temporal.io/sdk/internal.(*workflowEnvironmentInterceptor).ExecuteWorkflow(0xc00042a730?, {0xdfce40?, 0xc00043a580?}, {0xc00042e490?, 0xc0005a86c0?}, {0xc00042e4a0?, 0x1?, 0xc0001030c8?})
        /home/dnr/t/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/workflow.go:393 +0x1e5
go.temporal.io/sdk/internal.(*workflowExecutor).Execute(0xc00043a500, {0xdfce40, 0xc00043a580}, 0x25?)
        /home/dnr/t/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/internal_worker.go:762 +0x2c3
go.temporal.io/sdk/internal.(*syncWorkflowDefinition).Execute.func1({0xdfcfc8, 0xc00040d170})
        /home/dnr/t/go/pkg/mod/go.temporal.io/sdk@v1.6.0/internal/internal_workflow.go:494 +0xcd

```

Another weird thing I noticed was what was encoded in the marker:

```
{
  "data": {
    "payloads": [
      {
        "metadata": {"encoding": "anNvbi9wbGFpbg=="},
        "data": "ImRlZmF1bHROdW1iZXIi"
      },
      {
        "metadata": {"encoding": "anNvbi9wcm90b2J1Zg=="},
        "data": "eyJwYXlsb2FkcyI6W3sibWV0YWRhdGEiOnsiZW5jb2RpbmciOiJhbk52Ymk5d2JHRnBiZz09In0sImRhdGEiOiJNVGs9In1dfQ=="
      }
    ]
  },
  "side-effect-id": {
    "payloads": [
      {
        "metadata": {"encoding": "anNvbi9wbGFpbg=="},
        "data": "ImRlZmF1bHROdW1iZXIi"
      }
    ]
  }
}
```
Decoding all of that base64 to strings just to make things clear (pseudo-json):
```
{
  "data": {
    "payloads": [
      {
        "metadata": {"encoding": "json/plain"},
        "data": `"defaultNumber"`
      },
      {
        "metadata": {"encoding": "json/protobuf"},
        "data": `{"payloads":[{"metadata":{"encoding":"anNvbi9wbGFpbg=="},"data":"MTk="}]}`
      }
    ]
  },
  "side-effect-id": {
    "payloads": [
      {
        "metadata": {"encoding": "json/plain"},
        "data": `"defaultNumber"`
      }
    ]
  }
}
```
That is, the actual data is double-base64-encoded.

## Steps to Reproduce the Problem

Repro here: https://github.com/dnr/samples-go/tree/mutablesideeffect/helloworld

1. Run the worker
2. Run the starter
3. Kill the worker
4. Start the worker again

## Specifications

  - Version: tested go sdk 1.6.0 and also 1.14.0. server is a branch somewhere near 1.16.0. go 1.18
  - Platform: linux

**Comment by cretz** [comment]
@dnr - Thanks for the report! Can you give a bit more to your snippet? Specifically I am looking to see the `defaultNumber` variable and where it's defined.

I will attempt to replicate and fix shortly.

**Comment by cretz** [comment]
Ok, I have replicated this issue. It seems we have no good tests for mutable side effects :-( I have found two issues:

1. We do not properly unwrap the payloads from history that we wrap. It seems #151 wrapped them but didn't unwrap them on replay/history properly and there was no test to confirm it does
2. We are not recording a command during replay so there is a command mismatch

**Comment by cretz** [comment]
This is a much harder problem than it seems, and mutable side effects have never worker properly during replay.

Basically, the Go SDK maintains a counter so it can re-obtain things deterministically. This counter, which is incremented each command, is used for command IDs, timer IDs, cancellation IDs, signal IDs, upsert search attr IDs, etc.

When mutable side effect callback result _is not equal_ to the previous one during normal run, we record a marker command which increments the counter for all other commands. But we don't record a command if it _is equal_. During replay however, we can never know it is or isn't equal because we are not allowed to invoke the callback. So, do we record a command or not? If we don't get it right, the command counter mismatches causing non-determinism issues.

So, given a Go workflow that does:

1. WFT start (counter 5)
1. Mutable side effect not equal - record marker command (++counter)
1. Start a timer with ID 7 (++counter)
1. WFT end
1. Marker recorded
1. Timer 7 started
1. WFT start (counter 7)
1. Mutable side effect equal - *do not* record marker command
1. Start a timer with ID 8 (++counter)
1. WFT end
1. Timer 8 started

This is how replay looks if we _always_ record marker during replay

1. WFT start (counter 5)
1. Mutable side effect - record marker command (++counter)
1. Start a timer with ID 7 (++counter)
1. WFT end
1. Marker recorded
1. Timer 7 started
1. WFT start (counter 7)
1. Mutable side effect - record marker command (++counter) - note, we don't know equal vs not-equal here
1. Start a timer with ID 9 (++counter)
1. WFT end
1. Timer 8 started

That last step causes an error because timer 8 does not exist.

This is how replay looks if we _never_ record marker during replay (what the code does today):

1. WFT start (counter 5)
1. Mutable side effect - *do not* record marker command
1. Start a timer with ID 6 (++counter)
1. WFT end
1. Marker recorded (we don't error today if we don't know about the marker)
1. Timer 7 started

That last step causes an error because timer 7 does not exist.

So, what do we do here? Java seems to use a "fake" marker on every replay and just skips it when checking, but Go is not that fortunate because it has a counter that affects all things after it. Right now, here is the best solution I can think of:

* Track all replay markers recorded last WFT
* For every replay marker not recorded in history by the next WFT start, undo everything it did, which means I have to change past-recorded counter uses which includes:
  * Cancellation IDs for all pending cancel-external-workflow commands
  * Signal IDs for all pending signal-external-workflow commands
  * Upsert IDs for all pending upsert-search-attribute commands
  * Child workflow IDs for all pending execute-child-workflow commands. This is a bit complicated, because it only applies if they didn't provide their own workflow ID. When they don't provide it, it is `<parent-run-id>_<++counter>`. So I have to either check that it matches that pattern or maintain some state saying whether I auto-generated the ID so I can alter the generated value
  * Timer IDs for all pending timer commands
  * Schedule activity IDs for all pending execute-activity commands

Is there a better option here I am missing? cc @Sushisource, @mfateev, @yiminc, @alexshtin

**Comment by cretz** [comment]
OK, I have been able to use marker lookahead here. PR incoming...
