### ISSUE TITLE
temporal SDK not compatible with temporal API v1.9.0

### ISSUE THREAD

**Issue by gregorhollmig** [temporalio/sdk-go#832]
## Expected Behavior

I cannot build my service using temporal anymore.

With release v1.9.0 of https://github.com/temporalio/api-go/releases/tag/v1.9.0 the latest temporal SDK is not compatible anymore

## Actual Behavior

When building the service I get the message. Checking the latest code hier in master this is already adapted and I think just a release is required.

```
go.temporal.io/sdk/client/service_proxy.go:50:9: cannot use &workflowServiceProxyServer{…} (value of type *workflowServiceProxyServer) as type workflowservice.WorkflowServiceServer in return statement:
	*workflowServiceProxyServer does not implement workflowservice.WorkflowServiceServer (missing GetWorkerBuildIdOrdering method)
```

## Steps to Reproduce the Problem

1. Build application with latest temporal API&SDK

## Specifications

  - Version:  v1.15.0
  - Platform: MacOS

**Comment by cretz** [comment]
Yes, you have to use the dependency specified in the go.mod of the SDK version you are using. These are not meant to be upgraded independently.

(if you must use `v1.9.0` of the API dependency, you can use the latest `master`, but of course we always suggest a properly tagged release)

**Comment by twmb** [comment]
Technically, api-go's change was a breaking change, as evidenced here -- if I `go get -u ./...`, my compilation should not break.

There isn't really a great solution for this AFAICT since these are separate repos. In my own projects, once I've frozen an interface with 1.0, I've either added extension interfaces or bumped the major version.

**Comment by cretz** [comment]
> if I go get -u ./..., my compilation should not break.

In theory yes, however with many Go libraries these days, doing things such as adding a method to an interface in a point release is common sure to major version change hurtles.

> or bumped the major version

This is difficult in Go due to being forced to change everyone's import path (e.g. `/v2`)

> Are you already planning to release a new version of the go sdk with support for api v.1.9.0?

Yes, next release will have that. In the meantime, please continue to use the version required in go.mod or use `master` (not recommended of course).

**Comment by Tarang** [comment]
I'm receiving this error across multiple projects. I upgraded from temporal 1.12 to temporal 1.15 while building my project.

```
# go.temporal.io/sdk/client
../../../../go/pkg/mod/go.temporal.io/sdk@v1.15.0/client/service_proxy.go:50:9: cannot use &workflowServiceProxyServer{…} (value of type *workflowServiceProxyServer) as type workflowservice.WorkflowServiceServer in return statement:
        *workflowServiceProxyServer does not implement workflowservice.WorkflowServiceServer (missing GetWorkerBuildIdOrdering method)
```

I think its related to this issue.

**Comment by cretz** [comment]
> I have used go get -u to upgrade all my packages

You can't really do this with the current version. Rather you would just `go get go.temporal.io/sdk@latest` (not `-u`), but since you did `-u`, you can downgrade to the exact expected API version expected (`go get go.temporal.io/api@v1.8.0`).
