### ISSUE TITLE
Captures and reports panic/errors in an interceptor

### ISSUE THREAD

**Issue by qiuyuzhou** [temporalio/sdk-go#833]
I'm trying to implement an interceptor to capture all panic and errors from workflows and activities to [sentry](https://sentry.io) server.

My Question is:

Should I wrap the `Next.HandleSignal` execution in `WorkflowInboundInterceptor.HandleSignal` method.

I don't understand  temporal.io how to handle signal in internal. So I don't known how to write a test case to raise error captured in `WorkflowInboundInterceptor.HandleSignal`.

https://github.com/sdcxtech/sentrytemporal/blob/18f35d5db68bc29a34cc82d615edb092d6320bfa/workflow.go#L109

https://github.com/sdcxtech/sentrytemporal/blob/18f35d5db68bc29a34cc82d615edb092d6320bfa/tests/workflow_cases/worflow.go#L33

**Comment by cretz** [comment]
Since signals are handled via channels in Go, user code can't really panic/error the interceptor signal handler unless it was a user-defined interceptor signal handler panicking downstream. Basically the downstream final signal handler just puts it on the channel, so it can't really panic and the only error that can happen seems to be if it gets over 100k signals which is not really possible with history limits anyways.

So you probably don't need to worry about capturing panics/errors from signal handlers unless your concerned about a downstream interceptor.

**Comment by qiuyuzhou** [comment]
Thanks for your response!

I would remove the capturing for signal handler.
