### ISSUE TITLE
Panic with double stop on worker

### ISSUE THREAD

**Issue by yux0** [temporalio/sdk-go#855]
## Expected Behavior
Ignore the second stop

## Actual Behavior
panic: close of closed channel

https://github.com/temporalio/sdk-go/blob/master/internal/internal_worker.go#L1051
Can it check if the channel is closed using assertNotStopped()?

## Steps to Reproduce the Problem
Call worker.stop twice

**Comment by cretz** [comment]
> Ignore the second stop

I am not sure this is expected behavior anymore than a file can be closed/deleted twice.

Do we expect `Start` to be able to be called twice too? `Run` as well?

> Can it check if the channel is closed using assertNotStopped()?

That is not atomic though, so technically you could still get this panic.

We _could_ call this, but then it changes the behavior. I am not convinced we need to allow worker functions to be safe for multiple calls. If a user's code cannot know whether they have called stop, they can maintain such a state.

**Comment by cretz** [comment]
Closing after 3 weeks with no response. I will document that `Stop` cannot be called twice.
